# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [22]:
import pandas as pd
a = pd.DataFrame({
    "Name" :['Tanishq Patel','Atishay','Krishna','Raj','Agam'],
    'Age':[21,41,33,44,25] ,
    'Score': [70,65,70,80,85]
})
print(a)

#1. Single condition: rows where Age> 30
a[a['Age'] > 30]
a[a["Score"] >= 80]

#2. Multiple conditions  Age >= 25 Score > 80
a[(a['Age'] >= 25) &  (a["Score"] > 80)]
#(condition 1) operator(and[&] , or[|] ,not[~]) (condition 2)

a[(a['Age'] >= 25) |  (a["Score"] > 80)]

~a["Score"] > 80

            Name  Age  Score
0  Tanishq Patel   21     70
1        Atishay   41     65
2        Krishna   33     70
3            Raj   44     80
4           Agam   25     85

0    False
1    False
2    False
3    False
4    False
Name: Score, dtype: bool

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [32]:
#1. Age > 25 And Score >= 45
a[(a['Age'] >= 25) |  (a["Score"] > 45)]
#2. Age < 35 Or score >= 80
a[(a['Age']<  35) |  (a ["Score"] >= 80)]
#3. Age between 25 and 35(inclusive)
a[(a["Age"] >= 25)  & (a["Age"] <= 35)]

      Name  Age  Score
2  Krishna   33     70
4     Agam   25     85

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [35]:
#simple query: Age > 25
# in query we have type simple english
a.query('Age > 25')

#Age < 35 and Score >= 85
a.query("Age < 35 and Score >= 85")

s = 75
a.query("Score > @s") #-> dynamic filtering
#Note:- after @ their will be variable

   Name  Age  Score
3   Raj   44     80
4  Agam   25     85

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [43]:
# 1. convert to lower case to upper case
a['Name'].str.lower()

#2. conver to upper case to lowercase
a['Name'].str.upper()

#3. check if name comtains the letter 'a'
a[a['Name'].str.contains('a')]

#4. replace a substring to something else
a['Name'].str.replace('Agam','Agni')

#5. filter rows where name starts with "D"
a['Name'].str.startswith('D')

#6. filter rows where end starts with 'e'
a['Name'].str.endswith('e')

0    False
1    False
2    False
3    False
4    False
Name: Name, dtype: bool

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.