# 🐼 Final Pandas Assignment — Classes 1 to 6

### Level: Beginner → Intermediate → Practical

This assignment revises Classes 1–4 and gives **extra focus to Class 5 (Sorting & Basic Statistics)** and **Class 6 (GroupBy & Aggregations)**.

### Instructions
- Do **not** load a CSV file.
- When Class 6 starts, create the **8-column DataFrame in Q21**.
- Use that same DataFrame for the remaining Class 5 + Class 6 practice.
- Every question has an **Expected Output / I-O hint**.
- Write your solution in the blank code cell below each question.

### Class 6 Main Skills
`groupby()` • `agg()` • `pivot_table()` • `crosstab()`

# Part A — Pandas Basics & DataFrame Creation

### Q1. Import Pandas using the alias `pd`.

**Expected Output: Pandas is imported successfully.**

In [97]:
# Write your answer here
import pandas as pd

### Q2. Create a Series containing: `10, 20, 30, 40, 50`.

**Expected Output: A Series with 5 values.**

In [98]:
# Write your answer here
series = pd.Series([10,20,30,40,50])
series

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Q3. Create a small DataFrame with columns `Name`, `Age`, and `City` using a dictionary.

**Expected Output: A DataFrame with at least 5 rows.**

In [99]:
# Write your answer here
data = {'Name': ['Alice','Bob','Charlie','David','Eva'],
        'Age' : [1,22,33,44,55] ,
        'City':['New york','London','America','Paris','Tokyo']}
df = pd.DataFrame(data)
df

      Name  Age      City
0    Alice    1  New york
1      Bob   22    London
2  Charlie   33   America
3    David   44     Paris
4      Eva   55     Tokyo

### Q4. Display the first 3 rows using `head(3)`.

**Expected Output: First 3 rows are displayed.**

In [100]:
# Write your answer here
df.head(3)

      Name  Age      City
0    Alice    1  New york
1      Bob   22    London
2  Charlie   33   America

### Q5. Display the last 2 rows using `tail(2)`.

**Expected Output: Last 2 rows are displayed.**

In [101]:
# Write your answer here
df.tail(2)

    Name  Age   City
3  David   44  Paris
4    Eva   55  Tokyo

### Q6. Print the DataFrame `shape`, `columns`, and `index`.

**Expected Output: Shape, column names, and row index are displayed.**

In [102]:
# Write your answer here
df.shape

df.columns

df.index

RangeIndex(start=0, stop=5, step=1)

### Q7. Select one column and then select two columns together.

**Expected Output: A Series for one column and a DataFrame for two columns.**

### Q8. Use `loc` to select the first 3 rows.

**Expected Output: First 3 rows are displayed.**

In [103]:
# Write your answer here
first  = df.loc[0:2]
print(first)

      Name  Age      City
0    Alice    1  New york
1      Bob   22    London
2  Charlie   33   America

### Q9. Use `iloc` to select rows 1–3 and the first 2 columns.

**Expected Output: Required rows and columns are displayed.**

In [104]:
# Write your answer here
df.iloc[1:4,0:2]

      Name  Age
1      Bob   22
2  Charlie   33
3    David   44

### Q10. Rename one column using `rename()`.

**Expected Output: The selected column name is changed.**

In [105]:
# Write your answer here
df.rename(columns={'old_name' : 'new_name'},inplace=True)

### Q11. Find missing values using `isnull().sum()`.

**Expected Output: Missing-value count for every column.**

In [106]:
# Write your answer here
df.isnull().sum

<bound method DataFrame.sum of     Name    Age   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False>

### Q12. Use `fillna()` to replace a missing value in a numeric column.

**Expected Output: The missing value is filled.**

In [107]:
df.fillna(0)

      Name  Age      City
0    Alice    1  New york
1      Bob   22    London
2  Charlie   33   America
3    David   44     Paris
4      Eva   55     Tokyo

# Part B — Sorting & Basic Statistics (Class 5 Focus)

### Q13. Sort a numeric column in ascending order using `sort_values()`.

**Expected Output: Smallest value appears first.**

In [108]:
df.sort_values(by= "Age")

      Name  Age      City
0    Alice    1  New york
1      Bob   22    London
2  Charlie   33   America
3    David   44     Paris
4      Eva   55     Tokyo

### Q14. Sort the same column in descending order.

**Expected Output: Largest value appears first.**

In [109]:
# Write your answer here
df.sort_values(by = 'Age',ascending=False)

      Name  Age      City
4      Eva   55     Tokyo
3    David   44     Paris
2  Charlie   33   America
1      Bob   22    London
0    Alice    1  New york

### Q15. Sort by two columns: first by a categorical column and then by a numeric column.

**Expected Output: Data is grouped by the first column and sorted by the second within each group.**

In [110]:
# Write your answer here
df.sort_values(by=['City','Age'])

      Name  Age      City
2  Charlie   33   America
1      Bob   22    London
0    Alice    1  New york
3    David   44     Paris
4      Eva   55     Tokyo

### Q16. Use `sort_index()` to sort rows by their index.

**Expected Output: Index is in ascending order.**

In [111]:
# Write your answer here
df.sort_index()

      Name  Age      City
0    Alice    1  New york
1      Bob   22    London
2  Charlie   33   America
3    David   44     Paris
4      Eva   55     Tokyo

### Q17. Calculate the mean of a numeric column.

**Expected Output: One mean value.**

In [112]:
df.mean(numeric_only=True)

Age    31.0
dtype: float64

### Q18. Calculate the median and mode of a numeric column.

**Expected Output: Median and mode are displayed.**

In [113]:
# Write your answer here
df['Age'].median()
df['Age'].mode()

0     1
1    22
2    33
3    44
4    55
Name: Age, dtype: int64

### Q19. Calculate the standard deviation using `std()`.

**Expected Output: One standard-deviation value.**

In [114]:
# Write your answer here
df['Age'].std()

20.796634343085422

### Q20. Use `describe()` on the numeric columns.

**Expected Output: count, mean, std, min, quartiles, and max are displayed.**

In [115]:
# Write your answer here
df.describe()

             Age
count   5.000000
mean   31.000000
std    20.796634
min     1.000000
25%    22.000000
50%    33.000000
75%    44.000000
max    55.000000

# Part C — Create the Main 8-Column DataFrame (Class 6 Starts Here)

### Q21. Create this DataFrame with **8 columns**:

| Department | Employee | Salary | Age | City | Experience | Score | Gender |
|---|---|---:|---:|---|---:|---:|---|
| IT | Aman | 55000 | 24 | Delhi | 2 | 82 | M |
| HR | Neha | 48000 | 27 | Mumbai | 4 | 88 | F |
| IT | Ravi | 62000 | 29 | Pune | 5 | 91 | M |
| Sales | Priya | 45000 | 25 | Delhi | 3 | 76 | F |
| IT | Karan | 70000 | 32 | Bhopal | 8 | 95 | M |
| HR | Simran | 52000 | 30 | Delhi | 6 | 89 | F |
| Sales | Arjun | 50000 | 28 | Mumbai | 5 | 84 | M |
| IT | Pooja | 58000 | 26 | Pune | 3 | 87 | F |
| HR | Mohit | 46000 | 23 | Bhopal | 1 | 73 | M |
| Sales | Anjali | 54000 | 31 | Delhi | 7 | 92 | F |
| IT | Rahul | 65000 | 35 | Mumbai | 10 | 90 | M |
| HR | Isha | 50000 | 26 | Pune | 3 | 85 | F |

**Expected Output:** DataFrame with **12 rows and 8 columns**.

In [116]:
# Write your answer here
data = {'Department': ['IT','HR','IT','Sales','IT','HR','Sales','IT'],
        'Employee':['Aman','Neha','Ravi','Priya','Karan','Simran','Arjun','Pooja'],
        'Salary':[55000,48000,62000,45000,70000,52000,50000,58000],
        'Age':[24,27,29,25,32,30,28,26],
        'City':['Delhi','Mumbai','Pune','Delhi','Bhopal','Delhi','Mumbai',
        'Pune'],
        'Experience':[2,4,5,3,8,6,5,3],
        'Score':[82,88,91,76,95,89,84,87],
        'Gender':['M','F','M','F','M','F','M','F']}
df = pd.DataFrame(data)
df

  Department Employee  Salary  Age    City  Experience  Score Gender
0         IT     Aman   55000   24   Delhi           2     82      M
1         HR     Neha   48000   27  Mumbai           4     88      F
2         IT     Ravi   62000   29    Pune           5     91      M
3      Sales    Priya   45000   25   Delhi           3     76      F
4         IT    Karan   70000   32  Bhopal           8     95      M
5         HR   Simran   52000   30   Delhi           6     89      F
6      Sales    Arjun   50000   28  Mumbai           5     84      M
7         IT    Pooja   58000   26    Pune           3     87      F

### Q22. Display the first 5 rows of this DataFrame.

**Expected Output: Aman through Karan.**

In [117]:
# Write your answer here
df.head()

  Department Employee  Salary  Age    City  Experience  Score Gender
0         IT     Aman   55000   24   Delhi           2     82      M
1         HR     Neha   48000   27  Mumbai           4     88      F
2         IT     Ravi   62000   29    Pune           5     91      M
3      Sales    Priya   45000   25   Delhi           3     76      F
4         IT    Karan   70000   32  Bhopal           8     95      M

### Q23. Check the shape, columns, and data types.

**Expected Output: Shape is `(12, 8)`.**

In [118]:
# Write your answer here
df.shape
df.columns
df.dtypes

Department    object
Employee      object
Salary         int64
Age            int64
City          object
Experience     int64
Score          int64
Gender        object
dtype: object

# Part D — GroupBy & Aggregations (Main Focus)

### Q24. Group by `Department` and calculate the **average Salary**.

**Expected Output: One average Salary value for IT, HR, and Sales.**

In [119]:
# Write your answer here
df.groupby('Department')['Salary'].mean()

Department
HR       50000.0
IT       61250.0
Sales    47500.0
Name: Salary, dtype: float64

### Q25. Group by `Department` and calculate the **maximum Salary**.

**Expected Output: Maximum Salary for each department.**

In [120]:
# Write your answer here
df.groupby('Department')['Salary'].max()

Department
HR       52000
IT       70000
Sales    50000
Name: Salary, dtype: int64

### Q26. Group by `Department` and calculate the **minimum Age**.

**Expected Output: Minimum Age for each department.**

In [121]:
# Write your answer here
df.groupby('Department')['Age'].min()

Department
HR       27
IT       24
Sales    25
Name: Age, dtype: int64

### Q27. Group by `Department` and calculate the **number of employees**.

**Expected Output: IT = 5, HR = 4, Sales = 3.**

In [122]:
# Write your answer here
df.groupby('Department')['Employee'].count()

Department
HR       2
IT       4
Sales    2
Name: Employee, dtype: int64

### Q28. Group by `City` and calculate the average `Score`.

**Expected Output: One average Score for each city.**

In [123]:
# Write your answer here
df.groupby('City')['Score'].mean()

City
Bhopal    95.000000
Delhi     82.333333
Mumbai    86.000000
Pune      89.000000
Name: Score, dtype: float64

### Q29. Group by `Gender` and calculate the average `Salary`.

**Expected Output: Average Salary for M and F.**

In [124]:
# Write your answer here
df.groupby('Gender')['Salary'].mean()

Gender
F    50750.0
M    59250.0
Name: Salary, dtype: float64

### Q30. Use `groupby()` with `agg()` to find **mean Salary, maximum Age, and mean Score** for each Department.

**Expected Output: One row per department with 3 aggregated results.**

In [125]:
# Write your answer here
df.groupby('Department').agg({'Salary':'mean',
'Age': 'max',
  'Score' : 'mean'})

             Salary  Age  Score
Department
HR          50000.0   30  88.50
IT          61250.0   32  88.75
Sales       47500.0   28  80.00

### Q31. Use `agg()` to calculate **mean Salary and maximum Experience** for each Department.

**Expected Output: Department-wise mean Salary and max Experience.**

In [126]:
# Write your answer here
df.groupby('Department').agg({'Salary':'mean',
'Experience': 'max'})

             Salary  Experience
Department
HR          50000.0           6
IT          61250.0           8
Sales       47500.0           5

### Q32. Find the department with the **highest average Salary**.

**Expected Output: One department name.**

In [127]:
# Write your answer here
df.groupby('Department')['Salary'].mean().idxmax()

'IT'

### Q33. Find the city with the **highest average Score**.

**Expected Output: One city name.**

In [128]:
# Write your answer here
df.groupby('City')['Score'].mean().idxmax()

'Bhopal'

### Q34. Calculate the total Salary paid by each Department using `sum()`.

**Expected Output: Total salary for IT, HR, and Sales.**

In [129]:
# Write your answer here
df.groupby('Department')['Salary'].sum()

Department
HR       100000
IT       245000
Sales     95000
Name: Salary, dtype: int64

### Q35. Calculate the average Salary for each combination of `Department` and `Gender`.

**Expected Output: Department + Gender wise average Salary.**

In [130]:
# Write your answer here
df.groupby(['Department','Gender'])['Salary'].mean()

Department  Gender
HR          F         50000.000000
IT          F         58000.000000
            M         62333.333333
Sales       F         45000.000000
            M         50000.000000
Name: Salary, dtype: float64

# Part E — Pivot Table & Crosstab

### Q36. Create a pivot table showing **mean Salary by Department and City** using `pivot_table()`.

**Expected Output: Departments as rows, Cities as columns, mean Salary as values.**

In [131]:
# Write your answer here
pivot_table = df.pivot_table(index='Department', columns='City', values='Salary', aggfunc='mean')
print(pivot_table)

City         Bhopal    Delhi   Mumbai     Pune
Department
HR              NaN  52000.0  48000.0      NaN
IT          70000.0  55000.0      NaN  60000.0
Sales           NaN  45000.0  50000.0      NaN

### Q37. Create a pivot table showing **mean Score by Department and Gender**.

**Expected Output: Departments as rows, Gender as columns, mean Score as values.**

In [132]:
# Write your answer here
pivot_table = df.pivot_table(index='Department', columns='Gender', values='Score', aggfunc='mean')
print(pivot_table)

Gender         F          M
Department
HR          88.5        NaN
IT          87.0  89.333333
Sales       76.0  84.000000

### Q38. Create a crosstab showing the frequency of `Department` vs `City`.

**Expected Output: A frequency table with departments as rows and cities as columns.**

In [133]:
# Write your answer here
crosstab = pd.crosstab(df['Department'], df['City'])
print(crosstab)

City        Bhopal  Delhi  Mumbai  Pune
Department
HR               0      1       1     0
IT               1      1       0     2
Sales            0      1       1     0

### Q39. Create a crosstab showing `Department` vs `Gender`.

**Expected Output: Count of M/F employees in each department.**

In [134]:
# Write your answer here
pd.crosstab(df['Department'],df["Gender"])

Gender      F  M
Department
HR          2  0
IT          1  3
Sales       1  1

# Q40. ⭐ Final Practical Challenge

Using the same 8-column DataFrame:

1. Sort employees by `Salary` from highest to lowest.
2. Find the average Salary of each Department.
3. Find the Department with the highest average Salary.
4. Find the average Score by City.
5. Create a pivot table of mean Salary by Department and City.
6. Create a crosstab of Department vs Gender.

**Expected Result:** A small analysis report containing all six results.

In [135]:
# 1. Sort employees by Salary from highest to lowest
sorted_employees = df.sort_values(by='Salary', ascending=False)
print("--- 1. Sorted Employees by Salary ---")
print(sorted_employees.head(), "\n")

# 2. Find the average Salary of each Department
avg_salary_dept = df.groupby('Department')['Salary'].mean()
print("--- 2. Average Salary by Department ---")
print(avg_salary_dept, "\n")

# 3. Find the Department with the highest average Salary
highest_avg_salary_dept = avg_salary_dept.idxmax()
print("--- 3. Department with Highest Average Salary ---")
print(f"Department: {highest_avg_salary_dept}\n")

# 4. Find the average Score by City
# Note: Replace 'Score' with your actual column name if it differs (e.g., 'Performance_Score')
avg_score_city = df.groupby('City')['Score'].mean()
print("--- 4. Average Score by City ---")
print(avg_score_city, "\n")

# 5. Create a pivot table of mean Salary by Department and City
pivot_salary = df.pivot_table(values='Salary', index='Department', columns='City', aggfunc='mean')
print("--- 5. Pivot Table: Mean Salary by Dept and City ---")
print(pivot_salary, "\n")

# 6. Create a crosstab of Department vs Gender
crosstab_dept_gender = pd.crosstab(df['Department'], df['Gender'])
print("--- 6. Crosstab: Department vs Gender ---")
print(crosstab_dept_gender)

--- 1. Sorted Employees by Salary ---
  Department Employee  Salary  Age    City  Experience  Score Gender
4         IT    Karan   70000   32  Bhopal           8     95      M
2         IT     Ravi   62000   29    Pune           5     91      M
7         IT    Pooja   58000   26    Pune           3     87      F
0         IT     Aman   55000   24   Delhi           2     82      M
5         HR   Simran   52000   30   Delhi           6     89      F

--- 2. Average Salary by Department ---
Department
HR       50000.0
IT       61250.0
Sales    47500.0
Name: Salary, dtype: float64

--- 3. Department with Highest Average Salary ---
Department: IT

--- 4. Average Score by City ---
City
Bhopal    95.000000
Delhi     82.333333
Mumbai    86.000000
Pune      89.000000
Name: Score, dtype: float64

--- 5. Pivot Table: Mean Salary by Dept and City ---
City         Bhopal    Delhi   Mumbai     Pune
Department
HR              NaN  52000.0  48000.0      NaN
IT          70000.0  55000.0      NaN  60000.0
Sales           NaN  45000.0  50000.0      NaN

--- 6. Crosstab: Department vs Gender ---
Gender      F  M
Department
HR          2  0
IT          1  3
Sales       1  1

# ⭐ Bonus Challenge

Using the main DataFrame:

- Find the employee with the highest Salary.
- Find the employee with the highest Score.
- Find the Department with the highest total Salary.
- Find the City with the most employees.
- Find the average Experience of each Department.

Try to solve these using `groupby()`, `agg()`, sorting, and filtering.

In [136]:
# Bonus solution

df.loc[df["Salary"].idxmax()]

df.loc[df["Score"].idxmax()]

df.groupby("Department")["Salary"].sum().sort_values(ascending=False)

df.groupby("Department")["Salary"].sum().sort_values(ascending=False).head(1)

df.groupby("City").size().sort_values(ascending=False).head(1)

df.groupby("Department")["Experience"].mean()


df.groupby("Department").agg(
    Total_Salary=("Salary", "sum"),
    Average_Experience=("Experience", "mean"),
    Average_Score=("Score", "mean")
).sort_values("Total_Salary", ascending=False)

            Total_Salary  Average_Experience  Average_Score
Department
IT                245000                 4.5          88.75
HR                100000                 5.0          88.50
Sales              95000                 4.0          80.00